### ISSUE TITLE
Confirm what data is being processed

### ISSUE THREAD

**Issue by VeroniqueSvitkova** [jgraph/security-privacy-legal#3]
Hi, 
I found contradictory information about data that diagrams.net processes and we're struggling during our procurement process:
1. https://www.diagrams.net/trust/ => email, name, IP address (PII) and some other data
2. https://github.com/jgraph/security-privacy-legal/tree/master/Privacy/GDPR => no PII 
3. your support wrote me "draw.io does not process any data or PII."

Could you, please, clarify does diagrams.net process then?

**Comment by VeroniqueSvitkova** [comment]
Just to add on this - legally, no matter whether you use 3rd party tools or your own assets, it's still diagrams.net processing all the data. Just a remark on the sentence "draw.io doesn't process any data".

**Comment by davidjgraph** [comment]
But how? This is you running diagrams.net in your browser. You're executing that locally on your computer and the data is there.

**Comment by VeroniqueSvitkova** [comment]
The user is owning the data, but diagrams.net is processing them (I'm refering to any data that flows into your architecture/system/company/your suppliers, including logs, support emails, web tracking etc., as outlined here: https://www.diagrams.net/trust/).

**Comment by davidjgraph** [comment]
Nothing flows into our systems. We don't keep server logs. We don't provide support by email or any ticketing system. We don't perform web tracking. I'll update the page to reflect that.
