### ISSUE TITLE
Registration Country

### ISSUE THREAD

**Issue by chrisray79** [jgraph/security-privacy-legal#5]
Where is Draw.IO/Diagrams.net registration country?

**Comment by davidjgraph** [comment]
I'll seperate into one issue per issue, https://github.com/jgraph/security-privacy-legal/issues/6

"Where is Draw.IO/Diagrams.net registration country?" Registration of the company that runs the web app at app.diagrams.net?

**Comment by davidjgraph** [comment]
JGraph, the company behind diagrams.net, is a registered company in the UK.
